---
dependencies:
  - role: kubernetes-apps/ansible
    when:
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - apps

  - role: kubernetes-apps/efk
    when: efk_enabled
    tags:
    - apps
    - efk

  - role: kubernetes-apps/helm
    when:
      - helm_enabled
    tags:
      - apps
      - helm

  - role: kubernetes-apps/registry
    when:
      - registry_enabled
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - apps
      - registry

# istio role should be last because it takes a long time to initialize and
# will cause timeouts trying to start other addons.
  - role: kubernetes-apps/istio
    when: istio_enabled
    tags:
    - apps
    - istio

  - role: kubernetes-apps/metrics_server
    when:
      - metrics_server_enabled
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - apps
      - metrics_server

  - role: kubernetes-apps/persistent_volumes
    when:
      - persistent_volumes_enabled
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - apps
      - persistent_volumes

  - role: kubernetes-apps/container_engine_accelerator
    when: nvidia_accelerator_enabled
    tags:
      - apps
      - container_engine_accelerator

  - role: kubernetes-apps/cloud_controller/oci
    when:
      - cloud_provider is defined
      - cloud_provider == "oci"
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - oci
